
/*
Auto-generated by CVXPYgen on January 01, 2026 at 20:45:30.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_r0(0, 2400.00000000000000000000);
  cpg_update_v0(0, -10.00000000000000000000);
  cpg_update_log_m0(7.60090245954208221235);
  cpg_update_dt(0.57299999999999995381);
  cpg_update_dt_squared(0.32832899999999992646);
  cpg_update_g_dt_sq(0, -1.21810058999999970553);
  cpg_update_g_dt(0, -2.12582999999999966434);
  cpg_update_a_dt(0.00028649999999999997);
  cpg_update_sin_y_gs(0.49999999999999994449);
  cpg_update_cos_theta_deg(0.70710678118654757274);
  cpg_update_z0(0, 7.60090245954208221235);
  cpg_update_mu_1(0, 0.41666666666666662966);
  cpg_update_mu_2(0, 0.10416666666666665741);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<300; i++) {
    printf("r[%d] = %f\n", i, CPG_Result.prim->r[i]);
  }
  for(i=0; i<300; i++) {
    printf("v[%d] = %f\n", i, CPG_Result.prim->v[i]);
  }
  for(i=0; i<100; i++) {
    printf("z[%d] = %f\n", i, CPG_Result.prim->z[i]);
  }
  for(i=0; i<300; i++) {
    printf("u[%d] = %f\n", i, CPG_Result.prim->u[i]);
  }
  for(i=0; i<100; i++) {
    printf("s[%d] = %f\n", i, CPG_Result.prim->s[i]);
  }

  // Print dual solution
  for(i=0; i<3; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<3; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  printf("d3 = %f\n", CPG_Result.dual->d3);
  printf("d4 = %f\n", CPG_Result.dual->d4);
  for(i=0; i<3; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<3; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  printf("d7 = %f\n", CPG_Result.dual->d7);
  printf("d8 = %f\n", CPG_Result.dual->d8);
  printf("d9 = %f\n", CPG_Result.dual->d9);
  printf("d10 = %f\n", CPG_Result.dual->d10);
  printf("d11 = %f\n", CPG_Result.dual->d11);
  printf("d12 = %f\n", CPG_Result.dual->d12);
  printf("d13 = %f\n", CPG_Result.dual->d13);
  for(i=0; i<3; i++) {
    printf("d14[%d] = %f\n", i, CPG_Result.dual->d14[i]);
  }
  for(i=0; i<3; i++) {
    printf("d15[%d] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  printf("d16 = %f\n", CPG_Result.dual->d16);
  printf("d17 = %f\n", CPG_Result.dual->d17);
  printf("d18 = %f\n", CPG_Result.dual->d18);
  printf("d19 = %f\n", CPG_Result.dual->d19);
  printf("d20 = %f\n", CPG_Result.dual->d20);
  printf("d21 = %f\n", CPG_Result.dual->d21);
  printf("d22 = %f\n", CPG_Result.dual->d22);
  for(i=0; i<3; i++) {
    printf("d23[%d] = %f\n", i, CPG_Result.dual->d23[i]);
  }
  for(i=0; i<3; i++) {
    printf("d24[%d] = %f\n", i, CPG_Result.dual->d24[i]);
  }
  printf("d25 = %f\n", CPG_Result.dual->d25);
  printf("d26 = %f\n", CPG_Result.dual->d26);
  printf("d27 = %f\n", CPG_Result.dual->d27);
  printf("d28 = %f\n", CPG_Result.dual->d28);
  printf("d29 = %f\n", CPG_Result.dual->d29);
  printf("d30 = %f\n", CPG_Result.dual->d30);
  printf("d31 = %f\n", CPG_Result.dual->d31);
  for(i=0; i<3; i++) {
    printf("d32[%d] = %f\n", i, CPG_Result.dual->d32[i]);
  }
  for(i=0; i<3; i++) {
    printf("d33[%d] = %f\n", i, CPG_Result.dual->d33[i]);
  }
  printf("d34 = %f\n", CPG_Result.dual->d34);
  printf("d35 = %f\n", CPG_Result.dual->d35);
  printf("d36 = %f\n", CPG_Result.dual->d36);
  printf("d37 = %f\n", CPG_Result.dual->d37);
  printf("d38 = %f\n", CPG_Result.dual->d38);
  printf("d39 = %f\n", CPG_Result.dual->d39);
  printf("d40 = %f\n", CPG_Result.dual->d40);
  for(i=0; i<3; i++) {
    printf("d41[%d] = %f\n", i, CPG_Result.dual->d41[i]);
  }
  for(i=0; i<3; i++) {
    printf("d42[%d] = %f\n", i, CPG_Result.dual->d42[i]);
  }
  printf("d43 = %f\n", CPG_Result.dual->d43);
  printf("d44 = %f\n", CPG_Result.dual->d44);
  printf("d45 = %f\n", CPG_Result.dual->d45);
  printf("d46 = %f\n", CPG_Result.dual->d46);
  printf("d47 = %f\n", CPG_Result.dual->d47);
  printf("d48 = %f\n", CPG_Result.dual->d48);
  printf("d49 = %f\n", CPG_Result.dual->d49);
  for(i=0; i<3; i++) {
    printf("d50[%d] = %f\n", i, CPG_Result.dual->d50[i]);
  }
  for(i=0; i<3; i++) {
    printf("d51[%d] = %f\n", i, CPG_Result.dual->d51[i]);
  }
  printf("d52 = %f\n", CPG_Result.dual->d52);
  printf("d53 = %f\n", CPG_Result.dual->d53);
  printf("d54 = %f\n", CPG_Result.dual->d54);
  printf("d55 = %f\n", CPG_Result.dual->d55);
  printf("d56 = %f\n", CPG_Result.dual->d56);
  printf("d57 = %f\n", CPG_Result.dual->d57);
  printf("d58 = %f\n", CPG_Result.dual->d58);
  for(i=0; i<3; i++) {
    printf("d59[%d] = %f\n", i, CPG_Result.dual->d59[i]);
  }
  for(i=0; i<3; i++) {
    printf("d60[%d] = %f\n", i, CPG_Result.dual->d60[i]);
  }
  printf("d61 = %f\n", CPG_Result.dual->d61);
  printf("d62 = %f\n", CPG_Result.dual->d62);
  printf("d63 = %f\n", CPG_Result.dual->d63);
  printf("d64 = %f\n", CPG_Result.dual->d64);
  printf("d65 = %f\n", CPG_Result.dual->d65);
  printf("d66 = %f\n", CPG_Result.dual->d66);
  printf("d67 = %f\n", CPG_Result.dual->d67);
  for(i=0; i<3; i++) {
    printf("d68[%d] = %f\n", i, CPG_Result.dual->d68[i]);
  }
  for(i=0; i<3; i++) {
    printf("d69[%d] = %f\n", i, CPG_Result.dual->d69[i]);
  }
  printf("d70 = %f\n", CPG_Result.dual->d70);
  printf("d71 = %f\n", CPG_Result.dual->d71);
  printf("d72 = %f\n", CPG_Result.dual->d72);
  printf("d73 = %f\n", CPG_Result.dual->d73);
  printf("d74 = %f\n", CPG_Result.dual->d74);
  printf("d75 = %f\n", CPG_Result.dual->d75);
  printf("d76 = %f\n", CPG_Result.dual->d76);
  for(i=0; i<3; i++) {
    printf("d77[%d] = %f\n", i, CPG_Result.dual->d77[i]);
  }
  for(i=0; i<3; i++) {
    printf("d78[%d] = %f\n", i, CPG_Result.dual->d78[i]);
  }
  printf("d79 = %f\n", CPG_Result.dual->d79);
  printf("d80 = %f\n", CPG_Result.dual->d80);
  printf("d81 = %f\n", CPG_Result.dual->d81);
  printf("d82 = %f\n", CPG_Result.dual->d82);
  printf("d83 = %f\n", CPG_Result.dual->d83);
  printf("d84 = %f\n", CPG_Result.dual->d84);
  printf("d85 = %f\n", CPG_Result.dual->d85);
  for(i=0; i<3; i++) {
    printf("d86[%d] = %f\n", i, CPG_Result.dual->d86[i]);
  }
  for(i=0; i<3; i++) {
    printf("d87[%d] = %f\n", i, CPG_Result.dual->d87[i]);
  }
  printf("d88 = %f\n", CPG_Result.dual->d88);
  printf("d89 = %f\n", CPG_Result.dual->d89);
  printf("d90 = %f\n", CPG_Result.dual->d90);
  printf("d91 = %f\n", CPG_Result.dual->d91);
  printf("d92 = %f\n", CPG_Result.dual->d92);
  printf("d93 = %f\n", CPG_Result.dual->d93);
  printf("d94 = %f\n", CPG_Result.dual->d94);
  for(i=0; i<3; i++) {
    printf("d95[%d] = %f\n", i, CPG_Result.dual->d95[i]);
  }
  for(i=0; i<3; i++) {
    printf("d96[%d] = %f\n", i, CPG_Result.dual->d96[i]);
  }
  printf("d97 = %f\n", CPG_Result.dual->d97);
  printf("d98 = %f\n", CPG_Result.dual->d98);
  printf("d99 = %f\n", CPG_Result.dual->d99);
  printf("d100 = %f\n", CPG_Result.dual->d100);
  printf("d101 = %f\n", CPG_Result.dual->d101);
  printf("d102 = %f\n", CPG_Result.dual->d102);
  printf("d103 = %f\n", CPG_Result.dual->d103);
  for(i=0; i<3; i++) {
    printf("d104[%d] = %f\n", i, CPG_Result.dual->d104[i]);
  }
  for(i=0; i<3; i++) {
    printf("d105[%d] = %f\n", i, CPG_Result.dual->d105[i]);
  }
  printf("d106 = %f\n", CPG_Result.dual->d106);
  printf("d107 = %f\n", CPG_Result.dual->d107);
  printf("d108 = %f\n", CPG_Result.dual->d108);
  printf("d109 = %f\n", CPG_Result.dual->d109);
  printf("d110 = %f\n", CPG_Result.dual->d110);
  printf("d111 = %f\n", CPG_Result.dual->d111);
  printf("d112 = %f\n", CPG_Result.dual->d112);
  for(i=0; i<3; i++) {
    printf("d113[%d] = %f\n", i, CPG_Result.dual->d113[i]);
  }
  for(i=0; i<3; i++) {
    printf("d114[%d] = %f\n", i, CPG_Result.dual->d114[i]);
  }
  printf("d115 = %f\n", CPG_Result.dual->d115);
  printf("d116 = %f\n", CPG_Result.dual->d116);
  printf("d117 = %f\n", CPG_Result.dual->d117);
  printf("d118 = %f\n", CPG_Result.dual->d118);
  printf("d119 = %f\n", CPG_Result.dual->d119);
  printf("d120 = %f\n", CPG_Result.dual->d120);
  printf("d121 = %f\n", CPG_Result.dual->d121);
  for(i=0; i<3; i++) {
    printf("d122[%d] = %f\n", i, CPG_Result.dual->d122[i]);
  }
  for(i=0; i<3; i++) {
    printf("d123[%d] = %f\n", i, CPG_Result.dual->d123[i]);
  }
  printf("d124 = %f\n", CPG_Result.dual->d124);
  printf("d125 = %f\n", CPG_Result.dual->d125);
  printf("d126 = %f\n", CPG_Result.dual->d126);
  printf("d127 = %f\n", CPG_Result.dual->d127);
  printf("d128 = %f\n", CPG_Result.dual->d128);
  printf("d129 = %f\n", CPG_Result.dual->d129);
  printf("d130 = %f\n", CPG_Result.dual->d130);
  for(i=0; i<3; i++) {
    printf("d131[%d] = %f\n", i, CPG_Result.dual->d131[i]);
  }
  for(i=0; i<3; i++) {
    printf("d132[%d] = %f\n", i, CPG_Result.dual->d132[i]);
  }
  printf("d133 = %f\n", CPG_Result.dual->d133);
  printf("d134 = %f\n", CPG_Result.dual->d134);
  printf("d135 = %f\n", CPG_Result.dual->d135);
  printf("d136 = %f\n", CPG_Result.dual->d136);
  printf("d137 = %f\n", CPG_Result.dual->d137);
  printf("d138 = %f\n", CPG_Result.dual->d138);
  printf("d139 = %f\n", CPG_Result.dual->d139);
  for(i=0; i<3; i++) {
    printf("d140[%d] = %f\n", i, CPG_Result.dual->d140[i]);
  }
  for(i=0; i<3; i++) {
    printf("d141[%d] = %f\n", i, CPG_Result.dual->d141[i]);
  }
  printf("d142 = %f\n", CPG_Result.dual->d142);
  printf("d143 = %f\n", CPG_Result.dual->d143);
  printf("d144 = %f\n", CPG_Result.dual->d144);
  printf("d145 = %f\n", CPG_Result.dual->d145);
  printf("d146 = %f\n", CPG_Result.dual->d146);
  printf("d147 = %f\n", CPG_Result.dual->d147);
  printf("d148 = %f\n", CPG_Result.dual->d148);
  for(i=0; i<3; i++) {
    printf("d149[%d] = %f\n", i, CPG_Result.dual->d149[i]);
  }
  for(i=0; i<3; i++) {
    printf("d150[%d] = %f\n", i, CPG_Result.dual->d150[i]);
  }
  printf("d151 = %f\n", CPG_Result.dual->d151);
  printf("d152 = %f\n", CPG_Result.dual->d152);
  printf("d153 = %f\n", CPG_Result.dual->d153);
  printf("d154 = %f\n", CPG_Result.dual->d154);
  printf("d155 = %f\n", CPG_Result.dual->d155);
  printf("d156 = %f\n", CPG_Result.dual->d156);
  printf("d157 = %f\n", CPG_Result.dual->d157);
  for(i=0; i<3; i++) {
    printf("d158[%d] = %f\n", i, CPG_Result.dual->d158[i]);
  }
  for(i=0; i<3; i++) {
    printf("d159[%d] = %f\n", i, CPG_Result.dual->d159[i]);
  }
  printf("d160 = %f\n", CPG_Result.dual->d160);
  printf("d161 = %f\n", CPG_Result.dual->d161);
  printf("d162 = %f\n", CPG_Result.dual->d162);
  printf("d163 = %f\n", CPG_Result.dual->d163);
  printf("d164 = %f\n", CPG_Result.dual->d164);
  printf("d165 = %f\n", CPG_Result.dual->d165);
  printf("d166 = %f\n", CPG_Result.dual->d166);
  for(i=0; i<3; i++) {
    printf("d167[%d] = %f\n", i, CPG_Result.dual->d167[i]);
  }
  for(i=0; i<3; i++) {
    printf("d168[%d] = %f\n", i, CPG_Result.dual->d168[i]);
  }
  printf("d169 = %f\n", CPG_Result.dual->d169);
  printf("d170 = %f\n", CPG_Result.dual->d170);
  printf("d171 = %f\n", CPG_Result.dual->d171);
  printf("d172 = %f\n", CPG_Result.dual->d172);
  printf("d173 = %f\n", CPG_Result.dual->d173);
  printf("d174 = %f\n", CPG_Result.dual->d174);
  printf("d175 = %f\n", CPG_Result.dual->d175);
  for(i=0; i<3; i++) {
    printf("d176[%d] = %f\n", i, CPG_Result.dual->d176[i]);
  }
  for(i=0; i<3; i++) {
    printf("d177[%d] = %f\n", i, CPG_Result.dual->d177[i]);
  }
  printf("d178 = %f\n", CPG_Result.dual->d178);
  printf("d179 = %f\n", CPG_Result.dual->d179);
  printf("d180 = %f\n", CPG_Result.dual->d180);
  printf("d181 = %f\n", CPG_Result.dual->d181);
  printf("d182 = %f\n", CPG_Result.dual->d182);
  printf("d183 = %f\n", CPG_Result.dual->d183);
  printf("d184 = %f\n", CPG_Result.dual->d184);
  for(i=0; i<3; i++) {
    printf("d185[%d] = %f\n", i, CPG_Result.dual->d185[i]);
  }
  for(i=0; i<3; i++) {
    printf("d186[%d] = %f\n", i, CPG_Result.dual->d186[i]);
  }
  printf("d187 = %f\n", CPG_Result.dual->d187);
  printf("d188 = %f\n", CPG_Result.dual->d188);
  printf("d189 = %f\n", CPG_Result.dual->d189);
  printf("d190 = %f\n", CPG_Result.dual->d190);
  printf("d191 = %f\n", CPG_Result.dual->d191);
  printf("d192 = %f\n", CPG_Result.dual->d192);
  printf("d193 = %f\n", CPG_Result.dual->d193);
  for(i=0; i<3; i++) {
    printf("d194[%d] = %f\n", i, CPG_Result.dual->d194[i]);
  }
  for(i=0; i<3; i++) {
    printf("d195[%d] = %f\n", i, CPG_Result.dual->d195[i]);
  }
  printf("d196 = %f\n", CPG_Result.dual->d196);
  printf("d197 = %f\n", CPG_Result.dual->d197);
  printf("d198 = %f\n", CPG_Result.dual->d198);
  printf("d199 = %f\n", CPG_Result.dual->d199);
  printf("d200 = %f\n", CPG_Result.dual->d200);
  printf("d201 = %f\n", CPG_Result.dual->d201);
  printf("d202 = %f\n", CPG_Result.dual->d202);
  for(i=0; i<3; i++) {
    printf("d203[%d] = %f\n", i, CPG_Result.dual->d203[i]);
  }
  for(i=0; i<3; i++) {
    printf("d204[%d] = %f\n", i, CPG_Result.dual->d204[i]);
  }
  printf("d205 = %f\n", CPG_Result.dual->d205);
  printf("d206 = %f\n", CPG_Result.dual->d206);
  printf("d207 = %f\n", CPG_Result.dual->d207);
  printf("d208 = %f\n", CPG_Result.dual->d208);
  printf("d209 = %f\n", CPG_Result.dual->d209);
  printf("d210 = %f\n", CPG_Result.dual->d210);
  printf("d211 = %f\n", CPG_Result.dual->d211);
  for(i=0; i<3; i++) {
    printf("d212[%d] = %f\n", i, CPG_Result.dual->d212[i]);
  }
  for(i=0; i<3; i++) {
    printf("d213[%d] = %f\n", i, CPG_Result.dual->d213[i]);
  }
  printf("d214 = %f\n", CPG_Result.dual->d214);
  printf("d215 = %f\n", CPG_Result.dual->d215);
  printf("d216 = %f\n", CPG_Result.dual->d216);
  printf("d217 = %f\n", CPG_Result.dual->d217);
  printf("d218 = %f\n", CPG_Result.dual->d218);
  printf("d219 = %f\n", CPG_Result.dual->d219);
  printf("d220 = %f\n", CPG_Result.dual->d220);
  for(i=0; i<3; i++) {
    printf("d221[%d] = %f\n", i, CPG_Result.dual->d221[i]);
  }
  for(i=0; i<3; i++) {
    printf("d222[%d] = %f\n", i, CPG_Result.dual->d222[i]);
  }
  printf("d223 = %f\n", CPG_Result.dual->d223);
  printf("d224 = %f\n", CPG_Result.dual->d224);
  printf("d225 = %f\n", CPG_Result.dual->d225);
  printf("d226 = %f\n", CPG_Result.dual->d226);
  printf("d227 = %f\n", CPG_Result.dual->d227);
  printf("d228 = %f\n", CPG_Result.dual->d228);
  printf("d229 = %f\n", CPG_Result.dual->d229);
  for(i=0; i<3; i++) {
    printf("d230[%d] = %f\n", i, CPG_Result.dual->d230[i]);
  }
  for(i=0; i<3; i++) {
    printf("d231[%d] = %f\n", i, CPG_Result.dual->d231[i]);
  }
  printf("d232 = %f\n", CPG_Result.dual->d232);
  printf("d233 = %f\n", CPG_Result.dual->d233);
  printf("d234 = %f\n", CPG_Result.dual->d234);
  printf("d235 = %f\n", CPG_Result.dual->d235);
  printf("d236 = %f\n", CPG_Result.dual->d236);
  printf("d237 = %f\n", CPG_Result.dual->d237);
  printf("d238 = %f\n", CPG_Result.dual->d238);
  for(i=0; i<3; i++) {
    printf("d239[%d] = %f\n", i, CPG_Result.dual->d239[i]);
  }
  for(i=0; i<3; i++) {
    printf("d240[%d] = %f\n", i, CPG_Result.dual->d240[i]);
  }
  printf("d241 = %f\n", CPG_Result.dual->d241);
  printf("d242 = %f\n", CPG_Result.dual->d242);
  printf("d243 = %f\n", CPG_Result.dual->d243);
  printf("d244 = %f\n", CPG_Result.dual->d244);
  printf("d245 = %f\n", CPG_Result.dual->d245);
  printf("d246 = %f\n", CPG_Result.dual->d246);
  printf("d247 = %f\n", CPG_Result.dual->d247);
  for(i=0; i<3; i++) {
    printf("d248[%d] = %f\n", i, CPG_Result.dual->d248[i]);
  }
  for(i=0; i<3; i++) {
    printf("d249[%d] = %f\n", i, CPG_Result.dual->d249[i]);
  }
  printf("d250 = %f\n", CPG_Result.dual->d250);
  printf("d251 = %f\n", CPG_Result.dual->d251);
  printf("d252 = %f\n", CPG_Result.dual->d252);
  printf("d253 = %f\n", CPG_Result.dual->d253);
  printf("d254 = %f\n", CPG_Result.dual->d254);
  printf("d255 = %f\n", CPG_Result.dual->d255);
  printf("d256 = %f\n", CPG_Result.dual->d256);
  for(i=0; i<3; i++) {
    printf("d257[%d] = %f\n", i, CPG_Result.dual->d257[i]);
  }
  for(i=0; i<3; i++) {
    printf("d258[%d] = %f\n", i, CPG_Result.dual->d258[i]);
  }
  printf("d259 = %f\n", CPG_Result.dual->d259);
  printf("d260 = %f\n", CPG_Result.dual->d260);
  printf("d261 = %f\n", CPG_Result.dual->d261);
  printf("d262 = %f\n", CPG_Result.dual->d262);
  printf("d263 = %f\n", CPG_Result.dual->d263);
  printf("d264 = %f\n", CPG_Result.dual->d264);
  printf("d265 = %f\n", CPG_Result.dual->d265);
  for(i=0; i<3; i++) {
    printf("d266[%d] = %f\n", i, CPG_Result.dual->d266[i]);
  }
  for(i=0; i<3; i++) {
    printf("d267[%d] = %f\n", i, CPG_Result.dual->d267[i]);
  }
  printf("d268 = %f\n", CPG_Result.dual->d268);
  printf("d269 = %f\n", CPG_Result.dual->d269);
  printf("d270 = %f\n", CPG_Result.dual->d270);
  printf("d271 = %f\n", CPG_Result.dual->d271);
  printf("d272 = %f\n", CPG_Result.dual->d272);
  printf("d273 = %f\n", CPG_Result.dual->d273);
  printf("d274 = %f\n", CPG_Result.dual->d274);
  for(i=0; i<3; i++) {
    printf("d275[%d] = %f\n", i, CPG_Result.dual->d275[i]);
  }
  for(i=0; i<3; i++) {
    printf("d276[%d] = %f\n", i, CPG_Result.dual->d276[i]);
  }
  printf("d277 = %f\n", CPG_Result.dual->d277);
  printf("d278 = %f\n", CPG_Result.dual->d278);
  printf("d279 = %f\n", CPG_Result.dual->d279);
  printf("d280 = %f\n", CPG_Result.dual->d280);
  printf("d281 = %f\n", CPG_Result.dual->d281);
  printf("d282 = %f\n", CPG_Result.dual->d282);
  printf("d283 = %f\n", CPG_Result.dual->d283);
  for(i=0; i<3; i++) {
    printf("d284[%d] = %f\n", i, CPG_Result.dual->d284[i]);
  }
  for(i=0; i<3; i++) {
    printf("d285[%d] = %f\n", i, CPG_Result.dual->d285[i]);
  }
  printf("d286 = %f\n", CPG_Result.dual->d286);
  printf("d287 = %f\n", CPG_Result.dual->d287);
  printf("d288 = %f\n", CPG_Result.dual->d288);
  printf("d289 = %f\n", CPG_Result.dual->d289);
  printf("d290 = %f\n", CPG_Result.dual->d290);
  printf("d291 = %f\n", CPG_Result.dual->d291);
  printf("d292 = %f\n", CPG_Result.dual->d292);
  for(i=0; i<3; i++) {
    printf("d293[%d] = %f\n", i, CPG_Result.dual->d293[i]);
  }
  for(i=0; i<3; i++) {
    printf("d294[%d] = %f\n", i, CPG_Result.dual->d294[i]);
  }
  printf("d295 = %f\n", CPG_Result.dual->d295);
  printf("d296 = %f\n", CPG_Result.dual->d296);
  printf("d297 = %f\n", CPG_Result.dual->d297);
  printf("d298 = %f\n", CPG_Result.dual->d298);
  printf("d299 = %f\n", CPG_Result.dual->d299);
  printf("d300 = %f\n", CPG_Result.dual->d300);
  printf("d301 = %f\n", CPG_Result.dual->d301);
  for(i=0; i<3; i++) {
    printf("d302[%d] = %f\n", i, CPG_Result.dual->d302[i]);
  }
  for(i=0; i<3; i++) {
    printf("d303[%d] = %f\n", i, CPG_Result.dual->d303[i]);
  }
  printf("d304 = %f\n", CPG_Result.dual->d304);
  printf("d305 = %f\n", CPG_Result.dual->d305);
  printf("d306 = %f\n", CPG_Result.dual->d306);
  printf("d307 = %f\n", CPG_Result.dual->d307);
  printf("d308 = %f\n", CPG_Result.dual->d308);
  printf("d309 = %f\n", CPG_Result.dual->d309);
  printf("d310 = %f\n", CPG_Result.dual->d310);
  for(i=0; i<3; i++) {
    printf("d311[%d] = %f\n", i, CPG_Result.dual->d311[i]);
  }
  for(i=0; i<3; i++) {
    printf("d312[%d] = %f\n", i, CPG_Result.dual->d312[i]);
  }
  printf("d313 = %f\n", CPG_Result.dual->d313);
  printf("d314 = %f\n", CPG_Result.dual->d314);
  printf("d315 = %f\n", CPG_Result.dual->d315);
  printf("d316 = %f\n", CPG_Result.dual->d316);
  printf("d317 = %f\n", CPG_Result.dual->d317);
  printf("d318 = %f\n", CPG_Result.dual->d318);
  printf("d319 = %f\n", CPG_Result.dual->d319);
  for(i=0; i<3; i++) {
    printf("d320[%d] = %f\n", i, CPG_Result.dual->d320[i]);
  }
  for(i=0; i<3; i++) {
    printf("d321[%d] = %f\n", i, CPG_Result.dual->d321[i]);
  }
  printf("d322 = %f\n", CPG_Result.dual->d322);
  printf("d323 = %f\n", CPG_Result.dual->d323);
  printf("d324 = %f\n", CPG_Result.dual->d324);
  printf("d325 = %f\n", CPG_Result.dual->d325);
  printf("d326 = %f\n", CPG_Result.dual->d326);
  printf("d327 = %f\n", CPG_Result.dual->d327);
  printf("d328 = %f\n", CPG_Result.dual->d328);
  for(i=0; i<3; i++) {
    printf("d329[%d] = %f\n", i, CPG_Result.dual->d329[i]);
  }
  for(i=0; i<3; i++) {
    printf("d330[%d] = %f\n", i, CPG_Result.dual->d330[i]);
  }
  printf("d331 = %f\n", CPG_Result.dual->d331);
  printf("d332 = %f\n", CPG_Result.dual->d332);
  printf("d333 = %f\n", CPG_Result.dual->d333);
  printf("d334 = %f\n", CPG_Result.dual->d334);
  printf("d335 = %f\n", CPG_Result.dual->d335);
  printf("d336 = %f\n", CPG_Result.dual->d336);
  printf("d337 = %f\n", CPG_Result.dual->d337);
  for(i=0; i<3; i++) {
    printf("d338[%d] = %f\n", i, CPG_Result.dual->d338[i]);
  }
  for(i=0; i<3; i++) {
    printf("d339[%d] = %f\n", i, CPG_Result.dual->d339[i]);
  }
  printf("d340 = %f\n", CPG_Result.dual->d340);
  printf("d341 = %f\n", CPG_Result.dual->d341);
  printf("d342 = %f\n", CPG_Result.dual->d342);
  printf("d343 = %f\n", CPG_Result.dual->d343);
  printf("d344 = %f\n", CPG_Result.dual->d344);
  printf("d345 = %f\n", CPG_Result.dual->d345);
  printf("d346 = %f\n", CPG_Result.dual->d346);
  for(i=0; i<3; i++) {
    printf("d347[%d] = %f\n", i, CPG_Result.dual->d347[i]);
  }
  for(i=0; i<3; i++) {
    printf("d348[%d] = %f\n", i, CPG_Result.dual->d348[i]);
  }
  printf("d349 = %f\n", CPG_Result.dual->d349);
  printf("d350 = %f\n", CPG_Result.dual->d350);
  printf("d351 = %f\n", CPG_Result.dual->d351);
  printf("d352 = %f\n", CPG_Result.dual->d352);
  printf("d353 = %f\n", CPG_Result.dual->d353);
  printf("d354 = %f\n", CPG_Result.dual->d354);
  printf("d355 = %f\n", CPG_Result.dual->d355);
  for(i=0; i<3; i++) {
    printf("d356[%d] = %f\n", i, CPG_Result.dual->d356[i]);
  }
  for(i=0; i<3; i++) {
    printf("d357[%d] = %f\n", i, CPG_Result.dual->d357[i]);
  }
  printf("d358 = %f\n", CPG_Result.dual->d358);
  printf("d359 = %f\n", CPG_Result.dual->d359);
  printf("d360 = %f\n", CPG_Result.dual->d360);
  printf("d361 = %f\n", CPG_Result.dual->d361);
  printf("d362 = %f\n", CPG_Result.dual->d362);
  printf("d363 = %f\n", CPG_Result.dual->d363);
  printf("d364 = %f\n", CPG_Result.dual->d364);
  for(i=0; i<3; i++) {
    printf("d365[%d] = %f\n", i, CPG_Result.dual->d365[i]);
  }
  for(i=0; i<3; i++) {
    printf("d366[%d] = %f\n", i, CPG_Result.dual->d366[i]);
  }
  printf("d367 = %f\n", CPG_Result.dual->d367);
  printf("d368 = %f\n", CPG_Result.dual->d368);
  printf("d369 = %f\n", CPG_Result.dual->d369);
  printf("d370 = %f\n", CPG_Result.dual->d370);
  printf("d371 = %f\n", CPG_Result.dual->d371);
  printf("d372 = %f\n", CPG_Result.dual->d372);
  printf("d373 = %f\n", CPG_Result.dual->d373);
  for(i=0; i<3; i++) {
    printf("d374[%d] = %f\n", i, CPG_Result.dual->d374[i]);
  }
  for(i=0; i<3; i++) {
    printf("d375[%d] = %f\n", i, CPG_Result.dual->d375[i]);
  }
  printf("d376 = %f\n", CPG_Result.dual->d376);
  printf("d377 = %f\n", CPG_Result.dual->d377);
  printf("d378 = %f\n", CPG_Result.dual->d378);
  printf("d379 = %f\n", CPG_Result.dual->d379);
  printf("d380 = %f\n", CPG_Result.dual->d380);
  printf("d381 = %f\n", CPG_Result.dual->d381);
  printf("d382 = %f\n", CPG_Result.dual->d382);
  for(i=0; i<3; i++) {
    printf("d383[%d] = %f\n", i, CPG_Result.dual->d383[i]);
  }
  for(i=0; i<3; i++) {
    printf("d384[%d] = %f\n", i, CPG_Result.dual->d384[i]);
  }
  printf("d385 = %f\n", CPG_Result.dual->d385);
  printf("d386 = %f\n", CPG_Result.dual->d386);
  printf("d387 = %f\n", CPG_Result.dual->d387);
  printf("d388 = %f\n", CPG_Result.dual->d388);
  printf("d389 = %f\n", CPG_Result.dual->d389);
  printf("d390 = %f\n", CPG_Result.dual->d390);
  printf("d391 = %f\n", CPG_Result.dual->d391);
  for(i=0; i<3; i++) {
    printf("d392[%d] = %f\n", i, CPG_Result.dual->d392[i]);
  }
  for(i=0; i<3; i++) {
    printf("d393[%d] = %f\n", i, CPG_Result.dual->d393[i]);
  }
  printf("d394 = %f\n", CPG_Result.dual->d394);
  printf("d395 = %f\n", CPG_Result.dual->d395);
  printf("d396 = %f\n", CPG_Result.dual->d396);
  printf("d397 = %f\n", CPG_Result.dual->d397);
  printf("d398 = %f\n", CPG_Result.dual->d398);
  printf("d399 = %f\n", CPG_Result.dual->d399);
  printf("d400 = %f\n", CPG_Result.dual->d400);
  for(i=0; i<3; i++) {
    printf("d401[%d] = %f\n", i, CPG_Result.dual->d401[i]);
  }
  for(i=0; i<3; i++) {
    printf("d402[%d] = %f\n", i, CPG_Result.dual->d402[i]);
  }
  printf("d403 = %f\n", CPG_Result.dual->d403);
  printf("d404 = %f\n", CPG_Result.dual->d404);
  printf("d405 = %f\n", CPG_Result.dual->d405);
  printf("d406 = %f\n", CPG_Result.dual->d406);
  printf("d407 = %f\n", CPG_Result.dual->d407);
  printf("d408 = %f\n", CPG_Result.dual->d408);
  printf("d409 = %f\n", CPG_Result.dual->d409);
  for(i=0; i<3; i++) {
    printf("d410[%d] = %f\n", i, CPG_Result.dual->d410[i]);
  }
  for(i=0; i<3; i++) {
    printf("d411[%d] = %f\n", i, CPG_Result.dual->d411[i]);
  }
  printf("d412 = %f\n", CPG_Result.dual->d412);
  printf("d413 = %f\n", CPG_Result.dual->d413);
  printf("d414 = %f\n", CPG_Result.dual->d414);
  printf("d415 = %f\n", CPG_Result.dual->d415);
  printf("d416 = %f\n", CPG_Result.dual->d416);
  printf("d417 = %f\n", CPG_Result.dual->d417);
  printf("d418 = %f\n", CPG_Result.dual->d418);
  for(i=0; i<3; i++) {
    printf("d419[%d] = %f\n", i, CPG_Result.dual->d419[i]);
  }
  for(i=0; i<3; i++) {
    printf("d420[%d] = %f\n", i, CPG_Result.dual->d420[i]);
  }
  printf("d421 = %f\n", CPG_Result.dual->d421);
  printf("d422 = %f\n", CPG_Result.dual->d422);
  printf("d423 = %f\n", CPG_Result.dual->d423);
  printf("d424 = %f\n", CPG_Result.dual->d424);
  printf("d425 = %f\n", CPG_Result.dual->d425);
  printf("d426 = %f\n", CPG_Result.dual->d426);
  printf("d427 = %f\n", CPG_Result.dual->d427);
  for(i=0; i<3; i++) {
    printf("d428[%d] = %f\n", i, CPG_Result.dual->d428[i]);
  }
  for(i=0; i<3; i++) {
    printf("d429[%d] = %f\n", i, CPG_Result.dual->d429[i]);
  }
  printf("d430 = %f\n", CPG_Result.dual->d430);
  printf("d431 = %f\n", CPG_Result.dual->d431);
  printf("d432 = %f\n", CPG_Result.dual->d432);
  printf("d433 = %f\n", CPG_Result.dual->d433);
  printf("d434 = %f\n", CPG_Result.dual->d434);
  printf("d435 = %f\n", CPG_Result.dual->d435);
  printf("d436 = %f\n", CPG_Result.dual->d436);
  for(i=0; i<3; i++) {
    printf("d437[%d] = %f\n", i, CPG_Result.dual->d437[i]);
  }
  for(i=0; i<3; i++) {
    printf("d438[%d] = %f\n", i, CPG_Result.dual->d438[i]);
  }
  printf("d439 = %f\n", CPG_Result.dual->d439);
  printf("d440 = %f\n", CPG_Result.dual->d440);
  printf("d441 = %f\n", CPG_Result.dual->d441);
  printf("d442 = %f\n", CPG_Result.dual->d442);
  printf("d443 = %f\n", CPG_Result.dual->d443);
  printf("d444 = %f\n", CPG_Result.dual->d444);
  printf("d445 = %f\n", CPG_Result.dual->d445);
  for(i=0; i<3; i++) {
    printf("d446[%d] = %f\n", i, CPG_Result.dual->d446[i]);
  }
  for(i=0; i<3; i++) {
    printf("d447[%d] = %f\n", i, CPG_Result.dual->d447[i]);
  }
  printf("d448 = %f\n", CPG_Result.dual->d448);
  printf("d449 = %f\n", CPG_Result.dual->d449);
  printf("d450 = %f\n", CPG_Result.dual->d450);
  printf("d451 = %f\n", CPG_Result.dual->d451);
  printf("d452 = %f\n", CPG_Result.dual->d452);
  printf("d453 = %f\n", CPG_Result.dual->d453);
  printf("d454 = %f\n", CPG_Result.dual->d454);
  for(i=0; i<3; i++) {
    printf("d455[%d] = %f\n", i, CPG_Result.dual->d455[i]);
  }
  for(i=0; i<3; i++) {
    printf("d456[%d] = %f\n", i, CPG_Result.dual->d456[i]);
  }
  printf("d457 = %f\n", CPG_Result.dual->d457);
  printf("d458 = %f\n", CPG_Result.dual->d458);
  printf("d459 = %f\n", CPG_Result.dual->d459);
  printf("d460 = %f\n", CPG_Result.dual->d460);
  printf("d461 = %f\n", CPG_Result.dual->d461);
  printf("d462 = %f\n", CPG_Result.dual->d462);
  printf("d463 = %f\n", CPG_Result.dual->d463);
  for(i=0; i<3; i++) {
    printf("d464[%d] = %f\n", i, CPG_Result.dual->d464[i]);
  }
  for(i=0; i<3; i++) {
    printf("d465[%d] = %f\n", i, CPG_Result.dual->d465[i]);
  }
  printf("d466 = %f\n", CPG_Result.dual->d466);
  printf("d467 = %f\n", CPG_Result.dual->d467);
  printf("d468 = %f\n", CPG_Result.dual->d468);
  printf("d469 = %f\n", CPG_Result.dual->d469);
  printf("d470 = %f\n", CPG_Result.dual->d470);
  printf("d471 = %f\n", CPG_Result.dual->d471);
  printf("d472 = %f\n", CPG_Result.dual->d472);
  for(i=0; i<3; i++) {
    printf("d473[%d] = %f\n", i, CPG_Result.dual->d473[i]);
  }
  for(i=0; i<3; i++) {
    printf("d474[%d] = %f\n", i, CPG_Result.dual->d474[i]);
  }
  printf("d475 = %f\n", CPG_Result.dual->d475);
  printf("d476 = %f\n", CPG_Result.dual->d476);
  printf("d477 = %f\n", CPG_Result.dual->d477);
  printf("d478 = %f\n", CPG_Result.dual->d478);
  printf("d479 = %f\n", CPG_Result.dual->d479);
  printf("d480 = %f\n", CPG_Result.dual->d480);
  printf("d481 = %f\n", CPG_Result.dual->d481);
  for(i=0; i<3; i++) {
    printf("d482[%d] = %f\n", i, CPG_Result.dual->d482[i]);
  }
  for(i=0; i<3; i++) {
    printf("d483[%d] = %f\n", i, CPG_Result.dual->d483[i]);
  }
  printf("d484 = %f\n", CPG_Result.dual->d484);
  printf("d485 = %f\n", CPG_Result.dual->d485);
  printf("d486 = %f\n", CPG_Result.dual->d486);
  printf("d487 = %f\n", CPG_Result.dual->d487);
  printf("d488 = %f\n", CPG_Result.dual->d488);
  printf("d489 = %f\n", CPG_Result.dual->d489);
  printf("d490 = %f\n", CPG_Result.dual->d490);
  for(i=0; i<3; i++) {
    printf("d491[%d] = %f\n", i, CPG_Result.dual->d491[i]);
  }
  for(i=0; i<3; i++) {
    printf("d492[%d] = %f\n", i, CPG_Result.dual->d492[i]);
  }
  printf("d493 = %f\n", CPG_Result.dual->d493);
  printf("d494 = %f\n", CPG_Result.dual->d494);
  printf("d495 = %f\n", CPG_Result.dual->d495);
  printf("d496 = %f\n", CPG_Result.dual->d496);
  printf("d497 = %f\n", CPG_Result.dual->d497);
  printf("d498 = %f\n", CPG_Result.dual->d498);
  printf("d499 = %f\n", CPG_Result.dual->d499);
  for(i=0; i<3; i++) {
    printf("d500[%d] = %f\n", i, CPG_Result.dual->d500[i]);
  }
  for(i=0; i<3; i++) {
    printf("d501[%d] = %f\n", i, CPG_Result.dual->d501[i]);
  }
  printf("d502 = %f\n", CPG_Result.dual->d502);
  printf("d503 = %f\n", CPG_Result.dual->d503);
  printf("d504 = %f\n", CPG_Result.dual->d504);
  printf("d505 = %f\n", CPG_Result.dual->d505);
  printf("d506 = %f\n", CPG_Result.dual->d506);
  printf("d507 = %f\n", CPG_Result.dual->d507);
  printf("d508 = %f\n", CPG_Result.dual->d508);
  for(i=0; i<3; i++) {
    printf("d509[%d] = %f\n", i, CPG_Result.dual->d509[i]);
  }
  for(i=0; i<3; i++) {
    printf("d510[%d] = %f\n", i, CPG_Result.dual->d510[i]);
  }
  printf("d511 = %f\n", CPG_Result.dual->d511);
  printf("d512 = %f\n", CPG_Result.dual->d512);
  printf("d513 = %f\n", CPG_Result.dual->d513);
  printf("d514 = %f\n", CPG_Result.dual->d514);
  printf("d515 = %f\n", CPG_Result.dual->d515);
  printf("d516 = %f\n", CPG_Result.dual->d516);
  printf("d517 = %f\n", CPG_Result.dual->d517);
  for(i=0; i<3; i++) {
    printf("d518[%d] = %f\n", i, CPG_Result.dual->d518[i]);
  }
  for(i=0; i<3; i++) {
    printf("d519[%d] = %f\n", i, CPG_Result.dual->d519[i]);
  }
  printf("d520 = %f\n", CPG_Result.dual->d520);
  printf("d521 = %f\n", CPG_Result.dual->d521);
  printf("d522 = %f\n", CPG_Result.dual->d522);
  printf("d523 = %f\n", CPG_Result.dual->d523);
  printf("d524 = %f\n", CPG_Result.dual->d524);
  printf("d525 = %f\n", CPG_Result.dual->d525);
  printf("d526 = %f\n", CPG_Result.dual->d526);
  for(i=0; i<3; i++) {
    printf("d527[%d] = %f\n", i, CPG_Result.dual->d527[i]);
  }
  for(i=0; i<3; i++) {
    printf("d528[%d] = %f\n", i, CPG_Result.dual->d528[i]);
  }
  printf("d529 = %f\n", CPG_Result.dual->d529);
  printf("d530 = %f\n", CPG_Result.dual->d530);
  printf("d531 = %f\n", CPG_Result.dual->d531);
  printf("d532 = %f\n", CPG_Result.dual->d532);
  printf("d533 = %f\n", CPG_Result.dual->d533);
  printf("d534 = %f\n", CPG_Result.dual->d534);
  printf("d535 = %f\n", CPG_Result.dual->d535);
  for(i=0; i<3; i++) {
    printf("d536[%d] = %f\n", i, CPG_Result.dual->d536[i]);
  }
  for(i=0; i<3; i++) {
    printf("d537[%d] = %f\n", i, CPG_Result.dual->d537[i]);
  }
  printf("d538 = %f\n", CPG_Result.dual->d538);
  printf("d539 = %f\n", CPG_Result.dual->d539);
  printf("d540 = %f\n", CPG_Result.dual->d540);
  printf("d541 = %f\n", CPG_Result.dual->d541);
  printf("d542 = %f\n", CPG_Result.dual->d542);
  printf("d543 = %f\n", CPG_Result.dual->d543);
  printf("d544 = %f\n", CPG_Result.dual->d544);
  for(i=0; i<3; i++) {
    printf("d545[%d] = %f\n", i, CPG_Result.dual->d545[i]);
  }
  for(i=0; i<3; i++) {
    printf("d546[%d] = %f\n", i, CPG_Result.dual->d546[i]);
  }
  printf("d547 = %f\n", CPG_Result.dual->d547);
  printf("d548 = %f\n", CPG_Result.dual->d548);
  printf("d549 = %f\n", CPG_Result.dual->d549);
  printf("d550 = %f\n", CPG_Result.dual->d550);
  printf("d551 = %f\n", CPG_Result.dual->d551);
  printf("d552 = %f\n", CPG_Result.dual->d552);
  printf("d553 = %f\n", CPG_Result.dual->d553);
  for(i=0; i<3; i++) {
    printf("d554[%d] = %f\n", i, CPG_Result.dual->d554[i]);
  }
  for(i=0; i<3; i++) {
    printf("d555[%d] = %f\n", i, CPG_Result.dual->d555[i]);
  }
  printf("d556 = %f\n", CPG_Result.dual->d556);
  printf("d557 = %f\n", CPG_Result.dual->d557);
  printf("d558 = %f\n", CPG_Result.dual->d558);
  printf("d559 = %f\n", CPG_Result.dual->d559);
  printf("d560 = %f\n", CPG_Result.dual->d560);
  printf("d561 = %f\n", CPG_Result.dual->d561);
  printf("d562 = %f\n", CPG_Result.dual->d562);
  for(i=0; i<3; i++) {
    printf("d563[%d] = %f\n", i, CPG_Result.dual->d563[i]);
  }
  for(i=0; i<3; i++) {
    printf("d564[%d] = %f\n", i, CPG_Result.dual->d564[i]);
  }
  printf("d565 = %f\n", CPG_Result.dual->d565);
  printf("d566 = %f\n", CPG_Result.dual->d566);
  printf("d567 = %f\n", CPG_Result.dual->d567);
  printf("d568 = %f\n", CPG_Result.dual->d568);
  printf("d569 = %f\n", CPG_Result.dual->d569);
  printf("d570 = %f\n", CPG_Result.dual->d570);
  printf("d571 = %f\n", CPG_Result.dual->d571);
  for(i=0; i<3; i++) {
    printf("d572[%d] = %f\n", i, CPG_Result.dual->d572[i]);
  }
  for(i=0; i<3; i++) {
    printf("d573[%d] = %f\n", i, CPG_Result.dual->d573[i]);
  }
  printf("d574 = %f\n", CPG_Result.dual->d574);
  printf("d575 = %f\n", CPG_Result.dual->d575);
  printf("d576 = %f\n", CPG_Result.dual->d576);
  printf("d577 = %f\n", CPG_Result.dual->d577);
  printf("d578 = %f\n", CPG_Result.dual->d578);
  printf("d579 = %f\n", CPG_Result.dual->d579);
  printf("d580 = %f\n", CPG_Result.dual->d580);
  for(i=0; i<3; i++) {
    printf("d581[%d] = %f\n", i, CPG_Result.dual->d581[i]);
  }
  for(i=0; i<3; i++) {
    printf("d582[%d] = %f\n", i, CPG_Result.dual->d582[i]);
  }
  printf("d583 = %f\n", CPG_Result.dual->d583);
  printf("d584 = %f\n", CPG_Result.dual->d584);
  printf("d585 = %f\n", CPG_Result.dual->d585);
  printf("d586 = %f\n", CPG_Result.dual->d586);
  printf("d587 = %f\n", CPG_Result.dual->d587);
  printf("d588 = %f\n", CPG_Result.dual->d588);
  printf("d589 = %f\n", CPG_Result.dual->d589);
  for(i=0; i<3; i++) {
    printf("d590[%d] = %f\n", i, CPG_Result.dual->d590[i]);
  }
  for(i=0; i<3; i++) {
    printf("d591[%d] = %f\n", i, CPG_Result.dual->d591[i]);
  }
  printf("d592 = %f\n", CPG_Result.dual->d592);
  printf("d593 = %f\n", CPG_Result.dual->d593);
  printf("d594 = %f\n", CPG_Result.dual->d594);
  printf("d595 = %f\n", CPG_Result.dual->d595);
  printf("d596 = %f\n", CPG_Result.dual->d596);
  printf("d597 = %f\n", CPG_Result.dual->d597);
  printf("d598 = %f\n", CPG_Result.dual->d598);
  for(i=0; i<3; i++) {
    printf("d599[%d] = %f\n", i, CPG_Result.dual->d599[i]);
  }
  for(i=0; i<3; i++) {
    printf("d600[%d] = %f\n", i, CPG_Result.dual->d600[i]);
  }
  printf("d601 = %f\n", CPG_Result.dual->d601);
  printf("d602 = %f\n", CPG_Result.dual->d602);
  printf("d603 = %f\n", CPG_Result.dual->d603);
  printf("d604 = %f\n", CPG_Result.dual->d604);
  printf("d605 = %f\n", CPG_Result.dual->d605);
  printf("d606 = %f\n", CPG_Result.dual->d606);
  printf("d607 = %f\n", CPG_Result.dual->d607);
  for(i=0; i<3; i++) {
    printf("d608[%d] = %f\n", i, CPG_Result.dual->d608[i]);
  }
  for(i=0; i<3; i++) {
    printf("d609[%d] = %f\n", i, CPG_Result.dual->d609[i]);
  }
  printf("d610 = %f\n", CPG_Result.dual->d610);
  printf("d611 = %f\n", CPG_Result.dual->d611);
  printf("d612 = %f\n", CPG_Result.dual->d612);
  printf("d613 = %f\n", CPG_Result.dual->d613);
  printf("d614 = %f\n", CPG_Result.dual->d614);
  printf("d615 = %f\n", CPG_Result.dual->d615);
  printf("d616 = %f\n", CPG_Result.dual->d616);
  for(i=0; i<3; i++) {
    printf("d617[%d] = %f\n", i, CPG_Result.dual->d617[i]);
  }
  for(i=0; i<3; i++) {
    printf("d618[%d] = %f\n", i, CPG_Result.dual->d618[i]);
  }
  printf("d619 = %f\n", CPG_Result.dual->d619);
  printf("d620 = %f\n", CPG_Result.dual->d620);
  printf("d621 = %f\n", CPG_Result.dual->d621);
  printf("d622 = %f\n", CPG_Result.dual->d622);
  printf("d623 = %f\n", CPG_Result.dual->d623);
  printf("d624 = %f\n", CPG_Result.dual->d624);
  printf("d625 = %f\n", CPG_Result.dual->d625);
  for(i=0; i<3; i++) {
    printf("d626[%d] = %f\n", i, CPG_Result.dual->d626[i]);
  }
  for(i=0; i<3; i++) {
    printf("d627[%d] = %f\n", i, CPG_Result.dual->d627[i]);
  }
  printf("d628 = %f\n", CPG_Result.dual->d628);
  printf("d629 = %f\n", CPG_Result.dual->d629);
  printf("d630 = %f\n", CPG_Result.dual->d630);
  printf("d631 = %f\n", CPG_Result.dual->d631);
  printf("d632 = %f\n", CPG_Result.dual->d632);
  printf("d633 = %f\n", CPG_Result.dual->d633);
  printf("d634 = %f\n", CPG_Result.dual->d634);
  for(i=0; i<3; i++) {
    printf("d635[%d] = %f\n", i, CPG_Result.dual->d635[i]);
  }
  for(i=0; i<3; i++) {
    printf("d636[%d] = %f\n", i, CPG_Result.dual->d636[i]);
  }
  printf("d637 = %f\n", CPG_Result.dual->d637);
  printf("d638 = %f\n", CPG_Result.dual->d638);
  printf("d639 = %f\n", CPG_Result.dual->d639);
  printf("d640 = %f\n", CPG_Result.dual->d640);
  printf("d641 = %f\n", CPG_Result.dual->d641);
  printf("d642 = %f\n", CPG_Result.dual->d642);
  printf("d643 = %f\n", CPG_Result.dual->d643);
  for(i=0; i<3; i++) {
    printf("d644[%d] = %f\n", i, CPG_Result.dual->d644[i]);
  }
  for(i=0; i<3; i++) {
    printf("d645[%d] = %f\n", i, CPG_Result.dual->d645[i]);
  }
  printf("d646 = %f\n", CPG_Result.dual->d646);
  printf("d647 = %f\n", CPG_Result.dual->d647);
  printf("d648 = %f\n", CPG_Result.dual->d648);
  printf("d649 = %f\n", CPG_Result.dual->d649);
  printf("d650 = %f\n", CPG_Result.dual->d650);
  printf("d651 = %f\n", CPG_Result.dual->d651);
  printf("d652 = %f\n", CPG_Result.dual->d652);
  for(i=0; i<3; i++) {
    printf("d653[%d] = %f\n", i, CPG_Result.dual->d653[i]);
  }
  for(i=0; i<3; i++) {
    printf("d654[%d] = %f\n", i, CPG_Result.dual->d654[i]);
  }
  printf("d655 = %f\n", CPG_Result.dual->d655);
  printf("d656 = %f\n", CPG_Result.dual->d656);
  printf("d657 = %f\n", CPG_Result.dual->d657);
  printf("d658 = %f\n", CPG_Result.dual->d658);
  printf("d659 = %f\n", CPG_Result.dual->d659);
  printf("d660 = %f\n", CPG_Result.dual->d660);
  printf("d661 = %f\n", CPG_Result.dual->d661);
  for(i=0; i<3; i++) {
    printf("d662[%d] = %f\n", i, CPG_Result.dual->d662[i]);
  }
  for(i=0; i<3; i++) {
    printf("d663[%d] = %f\n", i, CPG_Result.dual->d663[i]);
  }
  printf("d664 = %f\n", CPG_Result.dual->d664);
  printf("d665 = %f\n", CPG_Result.dual->d665);
  printf("d666 = %f\n", CPG_Result.dual->d666);
  printf("d667 = %f\n", CPG_Result.dual->d667);
  printf("d668 = %f\n", CPG_Result.dual->d668);
  printf("d669 = %f\n", CPG_Result.dual->d669);
  printf("d670 = %f\n", CPG_Result.dual->d670);
  for(i=0; i<3; i++) {
    printf("d671[%d] = %f\n", i, CPG_Result.dual->d671[i]);
  }
  for(i=0; i<3; i++) {
    printf("d672[%d] = %f\n", i, CPG_Result.dual->d672[i]);
  }
  printf("d673 = %f\n", CPG_Result.dual->d673);
  printf("d674 = %f\n", CPG_Result.dual->d674);
  printf("d675 = %f\n", CPG_Result.dual->d675);
  printf("d676 = %f\n", CPG_Result.dual->d676);
  printf("d677 = %f\n", CPG_Result.dual->d677);
  printf("d678 = %f\n", CPG_Result.dual->d678);
  printf("d679 = %f\n", CPG_Result.dual->d679);
  for(i=0; i<3; i++) {
    printf("d680[%d] = %f\n", i, CPG_Result.dual->d680[i]);
  }
  for(i=0; i<3; i++) {
    printf("d681[%d] = %f\n", i, CPG_Result.dual->d681[i]);
  }
  printf("d682 = %f\n", CPG_Result.dual->d682);
  printf("d683 = %f\n", CPG_Result.dual->d683);
  printf("d684 = %f\n", CPG_Result.dual->d684);
  printf("d685 = %f\n", CPG_Result.dual->d685);
  printf("d686 = %f\n", CPG_Result.dual->d686);
  printf("d687 = %f\n", CPG_Result.dual->d687);
  printf("d688 = %f\n", CPG_Result.dual->d688);
  for(i=0; i<3; i++) {
    printf("d689[%d] = %f\n", i, CPG_Result.dual->d689[i]);
  }
  for(i=0; i<3; i++) {
    printf("d690[%d] = %f\n", i, CPG_Result.dual->d690[i]);
  }
  printf("d691 = %f\n", CPG_Result.dual->d691);
  printf("d692 = %f\n", CPG_Result.dual->d692);
  printf("d693 = %f\n", CPG_Result.dual->d693);
  printf("d694 = %f\n", CPG_Result.dual->d694);
  printf("d695 = %f\n", CPG_Result.dual->d695);
  printf("d696 = %f\n", CPG_Result.dual->d696);
  printf("d697 = %f\n", CPG_Result.dual->d697);
  for(i=0; i<3; i++) {
    printf("d698[%d] = %f\n", i, CPG_Result.dual->d698[i]);
  }
  for(i=0; i<3; i++) {
    printf("d699[%d] = %f\n", i, CPG_Result.dual->d699[i]);
  }
  printf("d700 = %f\n", CPG_Result.dual->d700);
  printf("d701 = %f\n", CPG_Result.dual->d701);
  printf("d702 = %f\n", CPG_Result.dual->d702);
  printf("d703 = %f\n", CPG_Result.dual->d703);
  printf("d704 = %f\n", CPG_Result.dual->d704);
  printf("d705 = %f\n", CPG_Result.dual->d705);
  printf("d706 = %f\n", CPG_Result.dual->d706);
  for(i=0; i<3; i++) {
    printf("d707[%d] = %f\n", i, CPG_Result.dual->d707[i]);
  }
  for(i=0; i<3; i++) {
    printf("d708[%d] = %f\n", i, CPG_Result.dual->d708[i]);
  }
  printf("d709 = %f\n", CPG_Result.dual->d709);
  printf("d710 = %f\n", CPG_Result.dual->d710);
  printf("d711 = %f\n", CPG_Result.dual->d711);
  printf("d712 = %f\n", CPG_Result.dual->d712);
  printf("d713 = %f\n", CPG_Result.dual->d713);
  printf("d714 = %f\n", CPG_Result.dual->d714);
  printf("d715 = %f\n", CPG_Result.dual->d715);
  for(i=0; i<3; i++) {
    printf("d716[%d] = %f\n", i, CPG_Result.dual->d716[i]);
  }
  for(i=0; i<3; i++) {
    printf("d717[%d] = %f\n", i, CPG_Result.dual->d717[i]);
  }
  printf("d718 = %f\n", CPG_Result.dual->d718);
  printf("d719 = %f\n", CPG_Result.dual->d719);
  printf("d720 = %f\n", CPG_Result.dual->d720);
  printf("d721 = %f\n", CPG_Result.dual->d721);
  printf("d722 = %f\n", CPG_Result.dual->d722);
  printf("d723 = %f\n", CPG_Result.dual->d723);
  printf("d724 = %f\n", CPG_Result.dual->d724);
  for(i=0; i<3; i++) {
    printf("d725[%d] = %f\n", i, CPG_Result.dual->d725[i]);
  }
  for(i=0; i<3; i++) {
    printf("d726[%d] = %f\n", i, CPG_Result.dual->d726[i]);
  }
  printf("d727 = %f\n", CPG_Result.dual->d727);
  printf("d728 = %f\n", CPG_Result.dual->d728);
  printf("d729 = %f\n", CPG_Result.dual->d729);
  printf("d730 = %f\n", CPG_Result.dual->d730);
  printf("d731 = %f\n", CPG_Result.dual->d731);
  printf("d732 = %f\n", CPG_Result.dual->d732);
  printf("d733 = %f\n", CPG_Result.dual->d733);
  for(i=0; i<3; i++) {
    printf("d734[%d] = %f\n", i, CPG_Result.dual->d734[i]);
  }
  for(i=0; i<3; i++) {
    printf("d735[%d] = %f\n", i, CPG_Result.dual->d735[i]);
  }
  printf("d736 = %f\n", CPG_Result.dual->d736);
  printf("d737 = %f\n", CPG_Result.dual->d737);
  printf("d738 = %f\n", CPG_Result.dual->d738);
  printf("d739 = %f\n", CPG_Result.dual->d739);
  printf("d740 = %f\n", CPG_Result.dual->d740);
  printf("d741 = %f\n", CPG_Result.dual->d741);
  printf("d742 = %f\n", CPG_Result.dual->d742);
  for(i=0; i<3; i++) {
    printf("d743[%d] = %f\n", i, CPG_Result.dual->d743[i]);
  }
  for(i=0; i<3; i++) {
    printf("d744[%d] = %f\n", i, CPG_Result.dual->d744[i]);
  }
  printf("d745 = %f\n", CPG_Result.dual->d745);
  printf("d746 = %f\n", CPG_Result.dual->d746);
  printf("d747 = %f\n", CPG_Result.dual->d747);
  printf("d748 = %f\n", CPG_Result.dual->d748);
  printf("d749 = %f\n", CPG_Result.dual->d749);
  printf("d750 = %f\n", CPG_Result.dual->d750);
  printf("d751 = %f\n", CPG_Result.dual->d751);
  for(i=0; i<3; i++) {
    printf("d752[%d] = %f\n", i, CPG_Result.dual->d752[i]);
  }
  for(i=0; i<3; i++) {
    printf("d753[%d] = %f\n", i, CPG_Result.dual->d753[i]);
  }
  printf("d754 = %f\n", CPG_Result.dual->d754);
  printf("d755 = %f\n", CPG_Result.dual->d755);
  printf("d756 = %f\n", CPG_Result.dual->d756);
  printf("d757 = %f\n", CPG_Result.dual->d757);
  printf("d758 = %f\n", CPG_Result.dual->d758);
  printf("d759 = %f\n", CPG_Result.dual->d759);
  printf("d760 = %f\n", CPG_Result.dual->d760);
  for(i=0; i<3; i++) {
    printf("d761[%d] = %f\n", i, CPG_Result.dual->d761[i]);
  }
  for(i=0; i<3; i++) {
    printf("d762[%d] = %f\n", i, CPG_Result.dual->d762[i]);
  }
  printf("d763 = %f\n", CPG_Result.dual->d763);
  printf("d764 = %f\n", CPG_Result.dual->d764);
  printf("d765 = %f\n", CPG_Result.dual->d765);
  printf("d766 = %f\n", CPG_Result.dual->d766);
  printf("d767 = %f\n", CPG_Result.dual->d767);
  printf("d768 = %f\n", CPG_Result.dual->d768);
  printf("d769 = %f\n", CPG_Result.dual->d769);
  for(i=0; i<3; i++) {
    printf("d770[%d] = %f\n", i, CPG_Result.dual->d770[i]);
  }
  for(i=0; i<3; i++) {
    printf("d771[%d] = %f\n", i, CPG_Result.dual->d771[i]);
  }
  printf("d772 = %f\n", CPG_Result.dual->d772);
  printf("d773 = %f\n", CPG_Result.dual->d773);
  printf("d774 = %f\n", CPG_Result.dual->d774);
  printf("d775 = %f\n", CPG_Result.dual->d775);
  printf("d776 = %f\n", CPG_Result.dual->d776);
  printf("d777 = %f\n", CPG_Result.dual->d777);
  printf("d778 = %f\n", CPG_Result.dual->d778);
  for(i=0; i<3; i++) {
    printf("d779[%d] = %f\n", i, CPG_Result.dual->d779[i]);
  }
  for(i=0; i<3; i++) {
    printf("d780[%d] = %f\n", i, CPG_Result.dual->d780[i]);
  }
  printf("d781 = %f\n", CPG_Result.dual->d781);
  printf("d782 = %f\n", CPG_Result.dual->d782);
  printf("d783 = %f\n", CPG_Result.dual->d783);
  printf("d784 = %f\n", CPG_Result.dual->d784);
  printf("d785 = %f\n", CPG_Result.dual->d785);
  printf("d786 = %f\n", CPG_Result.dual->d786);
  printf("d787 = %f\n", CPG_Result.dual->d787);
  for(i=0; i<3; i++) {
    printf("d788[%d] = %f\n", i, CPG_Result.dual->d788[i]);
  }
  for(i=0; i<3; i++) {
    printf("d789[%d] = %f\n", i, CPG_Result.dual->d789[i]);
  }
  printf("d790 = %f\n", CPG_Result.dual->d790);
  printf("d791 = %f\n", CPG_Result.dual->d791);
  printf("d792 = %f\n", CPG_Result.dual->d792);
  printf("d793 = %f\n", CPG_Result.dual->d793);
  printf("d794 = %f\n", CPG_Result.dual->d794);
  printf("d795 = %f\n", CPG_Result.dual->d795);
  printf("d796 = %f\n", CPG_Result.dual->d796);
  for(i=0; i<3; i++) {
    printf("d797[%d] = %f\n", i, CPG_Result.dual->d797[i]);
  }
  for(i=0; i<3; i++) {
    printf("d798[%d] = %f\n", i, CPG_Result.dual->d798[i]);
  }
  printf("d799 = %f\n", CPG_Result.dual->d799);
  printf("d800 = %f\n", CPG_Result.dual->d800);
  printf("d801 = %f\n", CPG_Result.dual->d801);
  printf("d802 = %f\n", CPG_Result.dual->d802);
  printf("d803 = %f\n", CPG_Result.dual->d803);
  printf("d804 = %f\n", CPG_Result.dual->d804);
  printf("d805 = %f\n", CPG_Result.dual->d805);
  for(i=0; i<3; i++) {
    printf("d806[%d] = %f\n", i, CPG_Result.dual->d806[i]);
  }
  for(i=0; i<3; i++) {
    printf("d807[%d] = %f\n", i, CPG_Result.dual->d807[i]);
  }
  printf("d808 = %f\n", CPG_Result.dual->d808);
  printf("d809 = %f\n", CPG_Result.dual->d809);
  printf("d810 = %f\n", CPG_Result.dual->d810);
  printf("d811 = %f\n", CPG_Result.dual->d811);
  printf("d812 = %f\n", CPG_Result.dual->d812);
  printf("d813 = %f\n", CPG_Result.dual->d813);
  printf("d814 = %f\n", CPG_Result.dual->d814);
  for(i=0; i<3; i++) {
    printf("d815[%d] = %f\n", i, CPG_Result.dual->d815[i]);
  }
  for(i=0; i<3; i++) {
    printf("d816[%d] = %f\n", i, CPG_Result.dual->d816[i]);
  }
  printf("d817 = %f\n", CPG_Result.dual->d817);
  printf("d818 = %f\n", CPG_Result.dual->d818);
  printf("d819 = %f\n", CPG_Result.dual->d819);
  printf("d820 = %f\n", CPG_Result.dual->d820);
  printf("d821 = %f\n", CPG_Result.dual->d821);
  printf("d822 = %f\n", CPG_Result.dual->d822);
  printf("d823 = %f\n", CPG_Result.dual->d823);
  for(i=0; i<3; i++) {
    printf("d824[%d] = %f\n", i, CPG_Result.dual->d824[i]);
  }
  for(i=0; i<3; i++) {
    printf("d825[%d] = %f\n", i, CPG_Result.dual->d825[i]);
  }
  printf("d826 = %f\n", CPG_Result.dual->d826);
  printf("d827 = %f\n", CPG_Result.dual->d827);
  printf("d828 = %f\n", CPG_Result.dual->d828);
  printf("d829 = %f\n", CPG_Result.dual->d829);
  printf("d830 = %f\n", CPG_Result.dual->d830);
  printf("d831 = %f\n", CPG_Result.dual->d831);
  printf("d832 = %f\n", CPG_Result.dual->d832);
  for(i=0; i<3; i++) {
    printf("d833[%d] = %f\n", i, CPG_Result.dual->d833[i]);
  }
  for(i=0; i<3; i++) {
    printf("d834[%d] = %f\n", i, CPG_Result.dual->d834[i]);
  }
  printf("d835 = %f\n", CPG_Result.dual->d835);
  printf("d836 = %f\n", CPG_Result.dual->d836);
  printf("d837 = %f\n", CPG_Result.dual->d837);
  printf("d838 = %f\n", CPG_Result.dual->d838);
  printf("d839 = %f\n", CPG_Result.dual->d839);
  printf("d840 = %f\n", CPG_Result.dual->d840);
  printf("d841 = %f\n", CPG_Result.dual->d841);
  for(i=0; i<3; i++) {
    printf("d842[%d] = %f\n", i, CPG_Result.dual->d842[i]);
  }
  for(i=0; i<3; i++) {
    printf("d843[%d] = %f\n", i, CPG_Result.dual->d843[i]);
  }
  printf("d844 = %f\n", CPG_Result.dual->d844);
  printf("d845 = %f\n", CPG_Result.dual->d845);
  printf("d846 = %f\n", CPG_Result.dual->d846);
  printf("d847 = %f\n", CPG_Result.dual->d847);
  printf("d848 = %f\n", CPG_Result.dual->d848);
  printf("d849 = %f\n", CPG_Result.dual->d849);
  printf("d850 = %f\n", CPG_Result.dual->d850);
  for(i=0; i<3; i++) {
    printf("d851[%d] = %f\n", i, CPG_Result.dual->d851[i]);
  }
  for(i=0; i<3; i++) {
    printf("d852[%d] = %f\n", i, CPG_Result.dual->d852[i]);
  }
  printf("d853 = %f\n", CPG_Result.dual->d853);
  printf("d854 = %f\n", CPG_Result.dual->d854);
  printf("d855 = %f\n", CPG_Result.dual->d855);
  printf("d856 = %f\n", CPG_Result.dual->d856);
  printf("d857 = %f\n", CPG_Result.dual->d857);
  printf("d858 = %f\n", CPG_Result.dual->d858);
  printf("d859 = %f\n", CPG_Result.dual->d859);
  for(i=0; i<3; i++) {
    printf("d860[%d] = %f\n", i, CPG_Result.dual->d860[i]);
  }
  for(i=0; i<3; i++) {
    printf("d861[%d] = %f\n", i, CPG_Result.dual->d861[i]);
  }
  printf("d862 = %f\n", CPG_Result.dual->d862);
  printf("d863 = %f\n", CPG_Result.dual->d863);
  printf("d864 = %f\n", CPG_Result.dual->d864);
  printf("d865 = %f\n", CPG_Result.dual->d865);
  printf("d866 = %f\n", CPG_Result.dual->d866);
  printf("d867 = %f\n", CPG_Result.dual->d867);
  printf("d868 = %f\n", CPG_Result.dual->d868);
  for(i=0; i<3; i++) {
    printf("d869[%d] = %f\n", i, CPG_Result.dual->d869[i]);
  }
  for(i=0; i<3; i++) {
    printf("d870[%d] = %f\n", i, CPG_Result.dual->d870[i]);
  }
  printf("d871 = %f\n", CPG_Result.dual->d871);
  printf("d872 = %f\n", CPG_Result.dual->d872);
  printf("d873 = %f\n", CPG_Result.dual->d873);
  printf("d874 = %f\n", CPG_Result.dual->d874);
  printf("d875 = %f\n", CPG_Result.dual->d875);
  printf("d876 = %f\n", CPG_Result.dual->d876);
  printf("d877 = %f\n", CPG_Result.dual->d877);
  for(i=0; i<3; i++) {
    printf("d878[%d] = %f\n", i, CPG_Result.dual->d878[i]);
  }
  for(i=0; i<3; i++) {
    printf("d879[%d] = %f\n", i, CPG_Result.dual->d879[i]);
  }
  printf("d880 = %f\n", CPG_Result.dual->d880);
  printf("d881 = %f\n", CPG_Result.dual->d881);
  printf("d882 = %f\n", CPG_Result.dual->d882);
  printf("d883 = %f\n", CPG_Result.dual->d883);
  printf("d884 = %f\n", CPG_Result.dual->d884);
  printf("d885 = %f\n", CPG_Result.dual->d885);
  printf("d886 = %f\n", CPG_Result.dual->d886);
  for(i=0; i<3; i++) {
    printf("d887[%d] = %f\n", i, CPG_Result.dual->d887[i]);
  }
  for(i=0; i<3; i++) {
    printf("d888[%d] = %f\n", i, CPG_Result.dual->d888[i]);
  }
  printf("d889 = %f\n", CPG_Result.dual->d889);
  printf("d890 = %f\n", CPG_Result.dual->d890);
  printf("d891 = %f\n", CPG_Result.dual->d891);
  printf("d892 = %f\n", CPG_Result.dual->d892);
  printf("d893 = %f\n", CPG_Result.dual->d893);
  printf("d894 = %f\n", CPG_Result.dual->d894);
  printf("d895 = %f\n", CPG_Result.dual->d895);
  printf("d896 = %f\n", CPG_Result.dual->d896);
  printf("d897 = %f\n", CPG_Result.dual->d897);
  printf("d898 = %f\n", CPG_Result.dual->d898);
  printf("d899 = %f\n", CPG_Result.dual->d899);
  printf("d900 = %f\n", CPG_Result.dual->d900);
  printf("d901 = %f\n", CPG_Result.dual->d901);

  return 0;

}
